name: reusable code-format

on: 
  push:
  workflow_dispatch:

jobs:
  format-code:
    uses: tjvans/github-config/.github/workflows/code-format.yml@main
    with:
      repo-token: ${{secrets.SHARED_WORKFLOW}}
