name: reusable code-format

on: 
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format-code:
    uses: tjvans/github-config/.github/workflows/code-format.yml@main
    secrets: inherit
