name: reusable gh-pages deploy

on:
  workflow_run:
    workflows: [code-format]
    types: [completed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    uses: tjvans/github-config/.github/workflows/vite-react-gh-pages-deploy.yml@main
    with:
      repo-token: ${{secrets.SHARED_WORKFLOW}}